nginx:
    build: ./nginx
    ports:
      - "8081:80"
    links:
      - "php"
    volumes:
      - ~/projects/docker/playDocker/opt:/opt

php:
    build: ./php
    ports:
      - "9000:9000"
    links:
      - "mysql"
    volumes:
      - ~/projects/docker/playDocker/opt:/opt

mysql:
    build: ./mysql
    ports:
      - "33060:3306"
    volumes:
      - ~/projects/docker/playDocker/opt/data/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456
